# Generated by Django 4.1.1 on 2022-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(upload_to='media/%Y/%m/%d/profile'),
        ),
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('coordinator', 'Coordinator'), ('inspector', 'Inspector')], max_length=20),
        ),
    ]
