# Generated by Django 4.1.1 on 2022-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('is_admin_viewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='jobassign',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
